
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class manageCoursesForm extends javax.swing.JFrame {

   
    course c=new course();
    public manageCoursesForm() {
        initComponents();
        c.fillCourseJtable(jTable1_courses);
        jTable1_courses.setRowHeight(40);
        jTable1_courses.setShowGrid(true);
        jTable1_courses.setGridColor(Color.DARK_GRAY);
        jTable1_courses.setSelectionBackground(Color.BLACK);
        jTable1_courses.setSelectionForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2_label = new javax.swing.JLabel();
        jTextField1_Courselabel = new javax.swing.JTextField();
        jLabel3_hours = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1_removeCourse = new javax.swing.JButton();
        jButton1_editCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_courses = new javax.swing.JTable();
        jLabel2_id = new javax.swing.JLabel();
        jTextField1_CourseId = new javax.swing.JTextField();
        jButton1_addCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage Courses");

        jLabel2_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2_label.setText("Label");

        jTextField1_Courselabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3_hours.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3_hours.setText("Hours");

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(3, 3, 250, 1));

        jButton1_removeCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove.png"))); // NOI18N
        jButton1_removeCourse.setText("Remove");
        jButton1_removeCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_removeCourseActionPerformed(evt);
            }
        });

        jButton1_editCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pen.png"))); // NOI18N
        jButton1_editCourse.setText("Edit");
        jButton1_editCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_editCourseActionPerformed(evt);
            }
        });

        jTable1_courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Label", "Hours"
            }
        ));
        jTable1_courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_coursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_courses);

        jLabel2_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2_id.setText("ID");

        jTextField1_CourseId.setEditable(false);
        jTextField1_CourseId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1_addCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        jButton1_addCourse.setText("Add");
        jButton1_addCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3_hours, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_Courselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_CourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1_removeCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_editCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1_addCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2_id)
                            .addComponent(jTextField1_CourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_Courselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_label))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3_hours)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_removeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_editCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_addCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_removeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_removeCourseActionPerformed
        
        //we have error here
         if(jTextField1_CourseId.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please Determine Course Id");
        }else
        {
        int cid=Integer.valueOf(jTextField1_CourseId.getText());
        c.insertUpdateDeleteCourse('d', cid, null, null);
        c.fillCourseJtable(jTable1_courses);
        jTable1_courses.setModel(new DefaultTableModel(null,new Object[]{"Id","Label","Hourse"}));
        c.fillCourseJtable(jTable1_courses);
        jTextField1_CourseId.setText("");
        jTextField1_Courselabel.setText("");
        jSpinner1.setValue(3);
            try {
                Mainform mf=new Mainform();
                mf.jLabel1_coursecount.setText("Courses Count = "+Integer.toString(MyFunction.countData("course")));
                
            } catch (SQLException ex) {
                Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Errrrr9rrrrrr in remove course");
            }
        }
    }//GEN-LAST:event_jButton1_removeCourseActionPerformed

    private void jButton1_editCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_editCourseActionPerformed

        //if(!c.isCourseExist(jTextField1_Courselabel.getText())){
            int id=Integer.valueOf(jTextField1_CourseId.getText());
             String label=jTextField1_Courselabel.getText();
             int hours=Integer.valueOf(jSpinner1.getValue().toString());
            c.insertUpdateDeleteCourse('u',id, label, hours); 
               
                manageCoursesForm.jTable1_courses.setModel(new DefaultTableModel(null,new Object[]{"Id","Label","Hours"}));
                c.fillCourseJtable(manageCoursesForm.jTable1_courses);
               // JOptionPane.showMessageDialog(null,"This Course Edited ");
        
    }//GEN-LAST:event_jButton1_editCourseActionPerformed

    private void jButton1_addCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addCourseActionPerformed
         addCourseForm add =new addCourseForm();
         add.setVisible(true);
         add.pack();
         add.setLocationRelativeTo(null);
         //when i close add student form don't close main form
         add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1_addCourseActionPerformed

    private void jTable1_coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_coursesMouseClicked
        
        int index=jTable1_courses.getSelectedRow();
        jTextField1_CourseId.setText(jTable1_courses.getValueAt(index,0).toString());
        jTextField1_Courselabel.setText(jTable1_courses.getValueAt(index,1).toString());
        jSpinner1.setValue(Integer.valueOf(jTable1_courses.getValueAt(index,2).toString()));
    }//GEN-LAST:event_jTable1_coursesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageCoursesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageCoursesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageCoursesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageCoursesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageCoursesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_addCourse;
    private javax.swing.JButton jButton1_editCourse;
    private javax.swing.JButton jButton1_removeCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_id;
    private javax.swing.JLabel jLabel2_label;
    private javax.swing.JLabel jLabel3_hours;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTable jTable1_courses;
    private javax.swing.JTextField jTextField1_CourseId;
    private javax.swing.JTextField jTextField1_Courselabel;
    // End of variables declaration//GEN-END:variables
}
