
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adel
 */
public class manageStudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form manageStudentsForm
     */
    student std=new student();
    DefaultTableModel model;
    public manageStudentsForm() {
        initComponents();
         ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1_male);
        bg.add(jRadioButton2_female);
        //jRadioButton1_male.setSelected(true);
        std.fillStudentJtable(jTable1, "");
        model=(DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.DARK_GRAY);
        jTable1.setSelectionBackground(Color.BLACK);
        jTable1.setSelectionForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2_fname = new javax.swing.JLabel();
        jLabel3_lname = new javax.swing.JLabel();
        jLabel4_gender = new javax.swing.JLabel();
        jLabel5_birthdate = new javax.swing.JLabel();
        jLabel6_phone = new javax.swing.JLabel();
        jLabel7_address = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jTextField2_lname = new javax.swing.JTextField();
        jTextField5_phone = new javax.swing.JTextField();
        jRadioButton1_male = new javax.swing.JRadioButton();
        jRadioButton2_female = new javax.swing.JRadioButton();
        jDateChooser1_birthdate = new com.toedter.calendar.JDateChooser();
        jButton1_edit = new javax.swing.JButton();
        jButton2_removeStudent = new javax.swing.JButton();
        jButton1_add = new javax.swing.JButton();
        jLabel8_id = new javax.swing.JLabel();
        jTextField1_fname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1_address = new javax.swing.JTextArea();
        jTextField1_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage Students");

        jLabel2_fname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2_fname.setText("First Name");

        jLabel3_lname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3_lname.setText("Last Name");

        jLabel4_gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4_gender.setText("Gender");

        jLabel5_birthdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5_birthdate.setText("Birthdate");

        jLabel6_phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6_phone.setText("Phone");

        jLabel7_address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7_address.setText("Address");

        jTextField1_id.setEditable(false);
        jTextField1_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField2_lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField5_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5_phoneKeyTyped(evt);
            }
        });

        jRadioButton1_male.setText("Male");

        jRadioButton2_female.setText("FeMale");

        jButton1_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pen.png"))); // NOI18N
        jButton1_edit.setText("Edit");
        jButton1_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_editActionPerformed(evt);
            }
        });

        jButton2_removeStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove.png"))); // NOI18N
        jButton2_removeStudent.setText("Remove");
        jButton2_removeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_removeStudentActionPerformed(evt);
            }
        });

        jButton1_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        jButton1_add.setText("Add");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });

        jLabel8_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8_id.setText("Id");

        jTextField1_fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Gender", "BirthDate", "Phone", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextArea1_address.setColumns(20);
        jTextArea1_address.setRows(5);
        jScrollPane2.setViewportView(jTextArea1_address);

        jTextField1_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1_searchKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Entre a value to search:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3_lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addComponent(jButton2_removeStudent)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jRadioButton2_female))
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5_birthdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1_male)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateChooser1_birthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5_phone)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_fname)
                            .addComponent(jTextField1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3_lname)
                            .addComponent(jTextField2_lname, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton2_female)
                                    .addComponent(jRadioButton1_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5_birthdate)
                            .addComponent(jDateChooser1_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6_phone)
                            .addComponent(jTextField5_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7_address)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2_removeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
          AddStudentForm add =new AddStudentForm();
        add.setVisible(true);
        add.pack();
        add.setLocationRelativeTo(null);
        //when i close add student form don't close main form
        add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void jButton2_removeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_removeStudentActionPerformed
        if(jTextField1_id.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please Determine Student Id");
        }else
        {
        int id=Integer.valueOf(jTextField1_id.getText());
        std.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);
        std.fillStudentJtable(jTable1,"");
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"}));
        std.fillStudentJtable(jTable1, jTextField1_search.getText());
            try {
                Mainform mf =new Mainform();
                mf.jLabel1_stdcount.setText("Students Count = "+Integer.toString(MyFunction.countData("student")));
                
                jTextArea1_address.setText("");
                jTextField1_fname.setText("");
                jTextField1_id.setText("");
                jTextField2_lname.setText("");
                jTextField5_phone.setText("");
                jRadioButton1_male.setSelected(false);
                jRadioButton2_female.setSelected(false);
                jDateChooser1_birthdate.setDate(null);
                
            } catch (SQLException ex) {
                Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Errrrrrrrrrrrrr9rrrrrr here");
            }
        }
    }//GEN-LAST:event_jButton2_removeStudentActionPerformed

     public boolean verifText(){
        if(jTextField1_id.getText().equals("")||jTextField1_fname.getText().equals("")||jTextField2_lname.getText().equals("")||jTextArea1_address.getText().equals("")
                ||jTextField5_phone.getText().equals("")||jDateChooser1_birthdate.getDate()==null)
        {
            JOptionPane.showMessageDialog(null,"One or more empty fields");
        return false;
        //choose a date heigher than current date;
        } else if(jDateChooser1_birthdate.getDate().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null,"No Student from the future is allowed");
        return false;
        }else
        return true;
    }
    private void jButton1_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_editActionPerformed

      String fname=jTextField1_fname.getText();
        String lname=jTextField2_lname.getText();
        String phone=jTextField5_phone.getText();
        String address=jTextArea1_address.getText();
        String gender="";
        int id=Integer.valueOf(jTextField1_id.getText());
                if(jRadioButton2_female.isSelected()){
                gender="FeMale";
                }else if(jRadioButton1_male.isSelected()){
                gender="Male";
                }
                if(verifText()){
                SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
                String bdate=dateformat.format(jDateChooser1_birthdate.getDate());
                
                student stdudent=new student();
                stdudent.insertUpdateDeleteStudent('u', id, fname, lname, gender, bdate, phone, address);
                 manageStudentsForm.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"}));
                 stdudent.fillStudentJtable(manageStudentsForm.jTable1, "");
           // Mainform.jLabel1_stdcount.setText("Students Count = "+Integer.toString(MyFunction.countData("student")));
                    
       
                }       

    }//GEN-LAST:event_jButton1_editActionPerformed

    private void jTextField5_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5_phoneKeyTyped
        // allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5_phoneKeyTyped

    int rowIndex;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        model=(DefaultTableModel)jTable1.getModel();
        rowIndex=jTable1.getSelectedRow();
        jRadioButton2_female.setSelected(true);
        jRadioButton1_male.setSelected(false);
        if(model.getValueAt(rowIndex, 3).toString().equals("male"))
        {
        jRadioButton1_male.setSelected(true);
        
        }else
        {
        jRadioButton2_female.setSelected(true);
        
        }
        jTextField1_id.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField1_fname.setText( model.getValueAt(rowIndex, 1).toString());
        jTextField2_lname.setText( model.getValueAt(rowIndex, 2).toString());
        jTextField5_phone.setText( model.getValueAt(rowIndex, 5).toString());
        jTextArea1_address.setText( model.getValueAt(rowIndex, 6).toString());
        
        Date bdate;
        try {
            bdate= new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooser1_birthdate.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_searchKeyTyped
      
    }//GEN-LAST:event_jTextField1_searchKeyTyped

    private void jTextField1_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_searchKeyPressed
        
    }//GEN-LAST:event_jTextField1_searchKeyPressed

    private void jTextField1_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_searchKeyReleased
         jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"}));
        std.fillStudentJtable(jTable1, jTextField1_search.getText());
    }//GEN-LAST:event_jTextField1_searchKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            rowIndex=jTable1.getSelectedRow();
        jTextField1_id.setText((String) model.getValueAt(rowIndex, 0));
        jTextField1_fname.setText((String) model.getValueAt(rowIndex, 1));
        jTextField2_lname.setText((String) model.getValueAt(rowIndex, 2));
        jTextField5_phone.setText((String) model.getValueAt(rowIndex, 5));
        jTextArea1_address.setText((String) model.getValueAt(rowIndex, 6));
         if(model.getValueAt(rowIndex, 3).toString().equals("Male"))
        {
        jRadioButton1_male.setSelected(true);
        jRadioButton2_female.setSelected(false);
        }else
        {
        jRadioButton2_female.setSelected(false);
        jRadioButton1_male.setSelected(false);
        }
        Date bdate;
        try {
            bdate= new SimpleDateFormat().parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooser1_birthdate.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageStudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton1_edit;
    private javax.swing.JButton jButton2_removeStudent;
    private com.toedter.calendar.JDateChooser jDateChooser1_birthdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_fname;
    private javax.swing.JLabel jLabel3_lname;
    private javax.swing.JLabel jLabel4_gender;
    private javax.swing.JLabel jLabel5_birthdate;
    private javax.swing.JLabel jLabel6_phone;
    private javax.swing.JLabel jLabel7_address;
    private javax.swing.JLabel jLabel8_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1_male;
    private javax.swing.JRadioButton jRadioButton2_female;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1_address;
    private javax.swing.JTextField jTextField1_fname;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField1_search;
    private javax.swing.JTextField jTextField2_lname;
    private javax.swing.JTextField jTextField5_phone;
    // End of variables declaration//GEN-END:variables
}
